### ISSUE TITLE
Motor driver and regulator

### ISSUE THREAD

**Issue by KocurMaros** [KocurMaros/MicroMouse#2]
Write driver for motor driver and create speed controller. 
Motor driver: TB6612FNG
MotorA:
Direction of rotation (Log.1/0):
    - GPIO18 CW
    - GPIO19 CCW
Speed(PWM):
    - GPIO17
MotorB:
Direction of rotation (Log.1/0):
    - GPIO16 CW
    - GPIO04 CCW
Speed(PWM):
    - GPIO02
Incremental encoder (interrupts):
MotorA:
    - GPIO34 ChannelA 
    - GPIO33 ChannelB
MotorB:
    - GPIO35 ChannelA 
    - GPIO32 ChannelB
https://www.faulhaber.com/fileadmin/Import/Media/EN_1717_SR_DFF.pdf
https://www.faulhaber.com/fileadmin/Import/Media/EN_IEH2-4096_DFF.pdf

**Comment by Fildo7525** [comment]
Review the code to be merged
